# Generated by Django 5.1 on 2024-08-25 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notebook', models.IntegerField()),
                ('projetor', models.IntegerField()),
                ('camera_fotorgrafica', models.IntegerField()),
                ('tripe_camera', models.IntegerField()),
                ('font_caix_som', models.IntegerField()),
                ('microfone', models.IntegerField()),
                ('caneta_lousa_interativa', models.IntegerField()),
                ('controle_tv', models.IntegerField()),
                ('controle_projetor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('equipamentos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='equipamentos', serialize=False, to='lista.equipamentos')),
                ('prof_instrutor', models.CharField(max_length=40)),
                ('sala', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=5)),
                ('data', models.DateField()),
            ],
        ),
    ]
