# Generated by Django 5.1 on 2024-08-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamentos',
            old_name='camera_fotorgrafica',
            new_name='camera_fotografica',
        ),
    ]
